#!/bin/sh

set -e

#----------------------------------------------------

if [ "$1" -eq 0 ] ; then
    if [ -z "$(ls -A /var/lib/hello/)" ]; then
        rm -rf /var/lib/hello/
    fi
fi

#----------------------------------------------------
exit 0
