#!/bin/sh

set -e

echo "+++ postinst " $@

[ -f /etc/default/hello ] && . /etc/default/hello

# Initial installation: $1 == configure
# Upgrade: $1 == configure, $2 == old version
case "$1" in
    configure)
        [ -z "$HELLO_USER" ] && HELLO_USER="hello"
        [ -z "$HELLO_GROUP" ] && HELLO_GROUP="hello"
        if ! getent group "$HELLO_GROUP" > /dev/null 2>&1 ; then
            groupadd -r "$HELLO_GROUP"
        fi
        if ! getent passwd "$HELLO_USER" > /dev/null 2>&1 ; then
            useradd -m -r -g "$HELLO_GROUP" -d /var/lib/hello -s /sbin/nologin -c "hello user" "$HELLO_USER"
        fi

        if getent group adm > /dev/null 2>&1 ; then
            usermod -a -G adm "$HELLO_USER"
        fi
        if getent group systemd-journal > /dev/null 2>&1 ; then
            usermod -a -G systemd-journal "$HELLO_USER"
        fi

        chown $HELLO_USER:$HELLO_GROUP /var/lib/hello
        chmod 770 /var/lib/hello

        if [ ! -d /var/lib/hello/data ]; then
            mkdir /var/lib/hello/data
            chown $HELLO_USER:$HELLO_GROUP /var/lib/hello/data
            chmod 770 /var/lib/hello/data
        fi

        chown root:$HELLO_GROUP /etc/hello
        chmod 770 /etc/hello

        if [ -z ${2+x} ] && [ "$RESTART_ON_UPGRADE" = "true" ]; then
            if command -v systemctl 2>/dev/null; then
                systemctl daemon-reload
                systemctl restart hello
            fi
        fi
esac
