version: 1

goos: linux
goarch: s390x

main: ./
binary: hello

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

flags:
  - -trimpath
  - -tags=netgo

ldflags:
  - "-w"
  - "-s"
  - '-extldflags "-static"'
  - "-X main.version={{ .Env.VERSION }}"
