#!/bin/sh

set -e

#----------------------------------------------------

echo "RUN postrm:" $@

if [ -z "$(ls -A /var/lib/hello/)" ]; then
    rm -rf /var/lib/hello/
fi

#----------------------------------------------------
exit 0
