#!/bin/sh

set -e

#----------------------------------------------------

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    if [ -z "$(ls -A /var/lib/hello/)" ]; then
        rm -rf /var/lib/hello/
    fi
fi

#----------------------------------------------------
exit 0
