#!/bin/sh

set -e

# Load environmental variables if exists.
[ -f /etc/default/hello ] && . /etc/default/hello

#----------------------------------------------------

echo "RUN prerm:" $@

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    if command -v systemctl 2>/dev/null; then
        systemctl stop hello.service > /dev/null 2>&1 || :
    fi
fi

#----------------------------------------------------
exit 0
