name: SLSA

on: push

permissions:
  id-token: write
  contents: write
  actions: read

jobs:
  build:
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.10.0
    strategy:
      matrix:
        os:
          - linux
        arch:
          - 386
          - amd64
          - arm
          - arm64
          - ppc64
          - ppc64le
          - riscv64
          - s390x
    with:
      go-version-file: ./go.mod
      config-file: .github/targets/${{matrix.os}}-${{matrix.arch}}.yaml
      evaluated-envs: "VERSION:v0.0.0"
      draft-release: true
      upload-assets: true
      upload-tag-name: v0.0.0

  fpm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
      - run: ls -la
      - run: |
          sudo apt-get update
          sudo apt-get install -y make ruby build-essential rpm
          sudo gem install fpm
          make all
          ls -la ./packages/
      - run: |
          cd ./packages/
          sha256sum ./hello-* >> ./SHA256SUMS
          sha1sum ./hello-* >> ./SHA1SUMS
          md5sum ./hello-* >> ./MD5SUMS
      - uses: actions/upload-artifact@v4
        with:
          name: fpm-packages
          path: ./packages/
      - uses: softprops/action-gh-release@v2
        with:
          files: ./packages/*
          draft: true
          tag_name: v0.0.0-fpm

  # Another example with https://nfpm.goreleaser.com/
  nfpm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
      - run: ls -la
      - run: |
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
          sudo apt-get update
          sudo apt-get install -y nfpm
          export NFPM_PASSPHRASE=hello
          make nfpm-all
          ls -la ./packages/
      - run: |
          cd ./packages/
          sha256sum ./hello-* >> ./SHA256SUMS
          sha1sum ./hello-* >> ./SHA1SUMS
          md5sum ./hello-* >> ./MD5SUMS
      - uses: actions/upload-artifact@v4
        with:
          name: nfpm-packages
          path: ./packages/
      - uses: softprops/action-gh-release@v2
        with:
          files: ./packages/*
          draft: true
          tag_name: v0.0.0-nfpm
