name: SLSA

on: push

permissions:
  id-token: write
  contents: write
  actions: read

jobs:
  build:
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.10.0
    strategy:
      matrix:
        os:
          - linux
        arch:
          - 386
          - amd64
          - arm
          - arm64
          - ppc64
          - ppc64le
          - riscv64
          - s390x
    with:
      go-version-file: ./go.mod
      config-file: .github/targets/${{matrix.os}}-${{matrix.arch}}.yaml
      evaluated-envs: "VERSION:v0.0.0"
      draft-release: true
      upload-assets: false
      upload-tag-name: v0.0.0

  list:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
      - run: ls -la
      - run: |
          sudo apt-get update
          sudo apt-get install -y make ruby build-essential rpm
          gem install fpm
          make all
          ls -la ./output/
